name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:14-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres

#      redis:
#        image: redis:alpine
#        ports: ['6379:6379']

    env:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis://localhost:6379/0
      RAILS_ENV: test
      DISABLE_SPRING: true
      CI: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          cache: yarn

      - name: Install Yarn packages
        run: bin/yarn install --frozen-lockfile

      - name: Lint with RuboCop
        run: bin/rubocop --parallel

#      - name: Run ESLint
#        run: bin/yarn lint
#
#      - name: Lint with SlimLint
#        run: bundle exec slim-lint .

      - name: Setup PostgreSQL
        run: bin/rails db:create

      - name: Compile assets
        run: bin/rails assets:precompile

      - name: Run Ruby Tests
        run: bin/rspec

  deploy:
    runs-on: ubuntu-20.04

#    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')

    needs: test

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tag annotations
        # https://github.com/actions/checkout/issues/290
        run: git fetch --tags --force

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the production image
        run: |
          export COMMIT_TIME=$(git show -s --format=%cI ${GITHUB_SHA})
          export COMMIT_VERSION=$(git describe --always)
          echo $GITHUB_SHA
          echo $COMMIT_TIME
          echo $COMMIT_VERSION
          docker buildx build --build-arg COMMIT_TIME --build-arg COMMIT_VERSION -t app .

      - name: Push the image tagged as LATEST to the container registry
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        run: |
          docker tag app ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Push the image tagged with version to the container registry
        if: startsWith(github.ref, 'refs/tags')
        run: |
          docker tag app ghcr.io/${{ github.repository }}:${GITHUB_REF##*/}
          docker push ghcr.io/${{ github.repository }}:${GITHUB_REF##*/}

#      - name: Send webhook to start deployment
#        env:
#          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
#        if: env.DEPLOY_HOOK != null
#        run: curl -X POST ${{ env.DEPLOY_HOOK }}

